const vscode = require('vscode');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
exports.run = async function () {
  const extension = vscode.extensions.getExtension('local-pi.pi-acp-workbench');
  assert(extension, 'Extension must be discovered');
  const api = await extension.activate();
  assert(extension.isActive, 'Extension activated');
  const commands = await vscode.commands.getCommands(true);
  assert(commands.includes('piAcp.preview') && commands.includes('piAcp.newSession'));
  await vscode.commands.executeCommand('piAcp.preview');
  assert(api.getState().preview, 'Offline preview state initialized');
  assert(api.getState().entries[0].text.includes('\\begin{align}'));
  const config = vscode.workspace.getConfiguration('piAcp');
  await config.update('command', 'node', vscode.ConfigurationTarget.Global);
  await config.update('args', [path.join(extension.extensionPath, 'test', 'mock-agent.mjs')], vscode.ConfigurationTarget.Global);
  await vscode.commands.executeCommand('piAcp.newSession');
  assert.equal(api.getState().status, 'ready', JSON.stringify(api.getState()));
  assert.equal(api.getState().sessionId, 'test-session');
  const doc = await vscode.workspace.openTextDocument({ content: 'const x = 1;', language: 'typescript' });
  // Use a saved file because context attachment intentionally requires a file-backed editor.
  const uri = vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri, 'context.ts');
  await vscode.workspace.fs.writeFile(uri, Buffer.from(doc.getText()));
  const editor = await vscode.window.showTextDocument(uri);
  editor.selection = new vscode.Selection(0, 0, 0, 5);
  await vscode.commands.executeCommand('piAcp.attachSelection');
  assert.equal(api.getState().attachments[0].text, 'const');
  await fs.writeFile(process.env.PI_HOST_TEST_RESULT, JSON.stringify({ passed: true, vscode: vscode.version, checks: ['activation', 'commands', 'offline preview', 'actual ACP stdio session', 'editor selection attachment'] }, null, 2));
};
